name: cvmaker
description: "Portfolio Maker - Create and manage your professional portfolio"
 
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

 
version: 1.0.0+1

environment:
  sdk: ^3.9.2

 
dependencies:
  flutter:
    sdk: flutter

 
  cupertino_icons: ^1.0.8
  
  # State management and navigation
  get: ^4.6.6
  
  # Local storage
  get_storage: ^2.1.1
  
  # Image picker
  image_picker: ^1.0.7
  
  # PDF generation
  pdf: ^3.11.1
  printing: ^5.13.3
  
  # File system access
  path_provider: ^2.1.2
  
  # Google Mobile Ads
  google_mobile_ads: ^5.1.0
  flutter_launcher_icons: ^0.14.4
  open_file: ^3.5.11  
  flutter_floating_bottom_bar: ^1.3.0
  google_fonts: ^8.0.2
  flutter_staggered_animations: ^1.1.1
  url_launcher: ^6.3.2
  share_plus: ^12.0.1
  intl: ^0.20.2
  appwrite: ^21.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter

 
  flutter_lints: ^5.0.0

flutter_icons: 
  android: true
  ios: true
  image_path: "assets/app_icon.png" 
 
flutter:
 
  uses-material-design: true

  # Add asset files
  assets:
    - assets/logo.png
    - assets/templates/

 